version: "3.9"

services:

  mysql:
    image: mysql:latest 
    container_name: ECONOBOT_DB
    environment:
      MYSQL_DATABASE: ${ECONOBOT_DB_NAME}
      MYSQL_PASSWORD: ${ECONOBOT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ECONOBOT_ROOT_PASSWORD} 
    ports:
      - "${ECONOBOT_DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql 

volumes:
  mysql_data:
